### ISSUE TITLE
all blank character page

### ISSUE THREAD

**Issue by QuebradaZN** [curruwilla/myaac#16]
After clicking on the name of some players, I would have to redirect to the page /?characters/NAMEDOPLAYER . but the screen is all white, is there any way to debug to present the errors, if it is lack of tables or something?
![site1](https://user-images.githubusercontent.com/47014952/162660774-c580cc32-6bc7-4972-ae60-ed10257290f4.PNG)

**Comment by curruwilla** [comment]
> 

Seu link parece estar quebrado, confere o **https://**

**Comment by QuebradaZN** [comment]
> > 
> 
> Seu link parece estar quebrado, confere o **https://**

Sim, Link está correto, https://gazarot.com/?highscores ,Clique em qualquer Char, Está com direcionamento corre, Acredito eu que falte alguma Tabela no Banco! (testei local e com IPV4 (sem o https) tambem sem sucesso!

**Comment by QuebradaZN** [comment]
Fixado!
sudo apt-get install php7.4-bcmath
sudo service apache2 restart

Estava faltando Modulo!
Abraço Rio Pretense!
