### ISSUE TITLE
URGENTE!

### ISSUE THREAD

**Issue by AdrianooTavares** [curruwilla/myaac#18]
preciso muito falar com você.... 
71 9 86890739 / meu whazap
AdrianoTavares#9352 ou meu discord

**Comment by curruwilla** [comment]
> preciso muito falar com você.... 71 9 86890739 / meu whazap AdrianoTavares#9352 ou meu discord

Não atualizo mais esse repositório Adriano, sugiro ir nos fóruns de OTServer..

**Comment by AdrianooTavares** [comment]
na verdade, queria fazer uma proposta para te!
